#!/bin/bash
# Hands-off ML Anthology corpus refresh.
#
# ONE WRITER, BY DESIGN. This script is the only thing that commits corpus data. The
# GitHub Actions cron was disabled deliberately: two independent writers on one branch
# diverge, and a diverged branch needs a human — the opposite of hands-off. The workflow
# stays available as a manual fallback via `gh workflow run "Update ML Anthology"`.
#
# It runs locally for a second measured reason: OpenReview answers a residential IP but
# returned 429 to the GitHub runners (2026-08-27), so the adapters get further from here.
#
# Chain: pull -> fetch adapters -> commit+push -> reindex -> re-probe the kernel lock.
# Deliberately NOT `set -e`: a failing adapter (one dead upstream) must never skip the
# reindex of whatever the other adapters did bring in.

set -uo pipefail

REPO="/Users/nathan/research/mlanthology"
SEARCH="$REPO/anthology-search"
KERNEL="/Users/nathan/research/kernel"
LOG="/Users/nathan/research/workspace/logs/mlarefresh.log"
LOCK="/tmp/mlarefresh.lock"

log() { printf '%s  %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*" >> "$LOG"; }

# Atomic mkdir lock: macOS has no flock(1). A stale lock older than 6h is reclaimed.
if ! mkdir "$LOCK" 2>/dev/null; then
    if [ -n "$(find "$LOCK" -maxdepth 0 -mmin +360 2>/dev/null)" ]; then
        log "WARN reclaiming stale lock"; rm -rf "$LOCK"; mkdir "$LOCK" 2>/dev/null || exit 0
    else
        log "SKIP another refresh is running"; exit 0
    fi
fi
trap 'rm -rf "$LOCK"' EXIT

log "=== refresh start ==="

# Optional local credentials (OpenReview). Kept OUTSIDE the repo; never committed.
# Create as: mkdir -p ~/.config/mlanthology && chmod 600 ~/.config/mlanthology/env
if [ -f "$HOME/.config/mlanthology/env" ]; then
    set -a; . "$HOME/.config/mlanthology/env"; set +a
    log "loaded local credentials"
fi

cd "$REPO" || { log "FATAL repo missing"; exit 1; }

# 1. Take anything the manual workflow may have pushed. ff-only: never auto-merge a
#    divergence, because silently resolving one is how corpus history gets mangled.
git fetch -q origin main 2>>"$LOG"
if ! git merge --ff-only origin/main >/dev/null 2>>"$LOG"; then
    log "WARN cannot fast-forward from origin/main — diverged, continuing on local state"
fi

# 2. Fetch — ONE SOURCE PER PROCESS, deliberately, not `--source all`.
#    fetch_all.py runs sources sequentially in a single process, so the first adapter
#    that raises kills every adapter after it. Measured 2026-08-27: OpenReview threw
#    ChallengeRequiredError and neurips, jmlr, cvf, ecva and acl never ran at all. One
#    dead upstream must cost one source, never the rest of the corpus.
#    dblp is excluded on purpose: it is a fill-only backlog tool, run by hand.
BEFORE=$(find "$REPO/data/papers" -name '*.json.gz' | wc -l | tr -d ' ')
FAILED=""
for SRC in pmlr openreview neurips jmlr cvf ecva acl; do
    if uv run --quiet --no-project --with-requirements requirements.txt \
           python scripts/fetch_all.py --source "$SRC" --no-build >>"$LOG" 2>&1; then
        log "  source $SRC ok"
    else
        log "  WARN source $SRC failed (continuing)"
        FAILED="$FAILED $SRC"
    fi
done
[ -n "$FAILED" ] && log "sources that failed:$FAILED" || log "all sources ok"
AFTER=$(find "$REPO/data/papers" -name '*.json.gz' | wc -l | tr -d ' ')

# 3. Commit + push, best effort. A failed push must not stop the local reindex —
#    the searchable corpus is the point; the remote is the backup.
if [ -n "$(git status --porcelain data/)" ]; then
    git add data/
    git commit -q -m "Update proceedings data [auto-refresh]

Files $BEFORE -> $AFTER. Generated by scripts/auto-refresh.sh." 2>>"$LOG"
    if git push -q origin main 2>>"$LOG"; then
        log "committed and pushed ($BEFORE -> $AFTER files)"
    else
        log "WARN commit made but push FAILED — remote is behind, local corpus is current"
    fi
else
    log "no corpus change"
fi

# 4. Reindex. Plain `mla index` is a no-op when the corpus has not moved.
if uv run --quiet --directory "$SEARCH" mla index >>"$LOG" 2>&1; then
    log "index current"
else
    log "ERROR reindex failed — searches will answer from the previous index"
fi

# 5. Re-record ONLY the mla block in kernel.lock (D-053 per-block merge). A full
#    `doctor --probe` would also re-probe every roster model and rewrite unrelated
#    blocks, which an unattended job has no business doing.
uv run --quiet --project "$KERNEL" python - >>"$LOG" 2>&1 <<'PY'
from pathlib import Path
from kernel.probe import probe_mla, record
home = Path("/Users/nathan/research/kernel")
block = probe_mla(home)
record(home, {"mla": block})
print(f"  lock: papers={block.get('papers')} sha={str(block.get('corpus_sha'))[:12]} stale={block.get('stale')}")
PY
[ $? -eq 0 ] && log "kernel.lock mla block re-recorded" || log "WARN lock update failed"

# 6. Commit that lock change — but ONLY when kernel.lock is the sole modification on a
#    clean main. Otherwise the weekly run leaves a dirty harness tree every Monday, which
#    is not hands-off; and committing into a branch mid-campaign would be worse. When the
#    tree is busy we skip and say so, and the change simply rides along with the chair's
#    next `kernel doctor --probe`. Note `kernel` is a .zshrc FUNCTION and does not exist
#    under launchd, so it is invoked through uv.
cd "$KERNEL" || exit 0
BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
CHANGED=$(git status --porcelain 2>/dev/null | awk '{print $NF}' | tr '\n' ' ' | sed 's/ *$//')
if [ "$BRANCH" = "main" ] && [ "$CHANGED" = "kernel.lock" ]; then
    if KERNEL_ROLE=build uv run --quiet --project "$KERNEL" kernel commit \
         -m "[build @ MR-0000] record: weekly corpus refresh — mla lock block re-probed by com.local.mlarefresh (papers/corpus_sha/commit follow the corpus; per-block merge, D-053, so no other capability is touched)" \
         >>"$LOG" 2>&1; then
        if git push -q origin HEAD 2>>"$LOG"; then
            log "kernel.lock committed and pushed"
        else
            log "WARN kernel.lock committed, push failed"
        fi
    else
        log "WARN kernel.lock commit failed — tree left modified"
    fi
elif [ -z "$CHANGED" ]; then
    log "kernel.lock unchanged"
else
    log "SKIP lock commit — harness busy (branch=$BRANCH, changed: $CHANGED); lock left modified"
fi

log "=== refresh done ==="
